function filename = build_filename(pars)

filename = strcat(pars.prob, pars.mg_opt,...
                    '_dir_',pars.direct_search,...
                    '_MG_',pars.enable_mg,...
                    '_SM_',num2str(pars.iter_smooth), ...
                    '_up_',num2str(pars.lev_finest), ...
                    '_low_',num2str(pars.lev_coarest));